### PR TITLE
fix(generate): write files in async task - fixes #363

### LINKED ISSUE #363: creating excel-functions fails because async method is treated as sync
The following error happens with `generator-office@1.1.17` 

internally `git.clone` is used which is async, but the `writing` method calls `_copyProjectFiles` sync. The following step in workflow *installing dependencies* throws because clone operation isn't finished yet.

This affects #360 and #362

### PR DESCRIPTION
**Pull request by ThorstenHans**
When templates come from an external repo, git.clone is used to pull the template. This method is async, so the generator has to wait until cloning actually finished

### CODE REVIEW

**Comment by TCourtneyOwen** [comment]
While I personally haven't hit any issues related to the cloning process, this change looks safe and an improvement to what we currently have. I know @akrantz was thinking that we could perhaps just have the cloning portion wrapped up in a promise, but I am personally OK with @ThorstenHans approach

File: src/app/index.ts [hunk 1]
```diff
@@ -181,7 +181,15 @@ module.exports = yo.extend({
   },
 
   writing: function () {
-    this._copyProjectFiles();
+    const done = this.async();
+    this._copyProjectFiles()
+    .then(() => {
```
Comment (akrantz) [inline src/app/index.ts]: This can be simplified as `.then(done)`

File: src/app/index.ts [hunk 2]
```diff
@@ -181,7 +181,15 @@ module.exports = yo.extend({
   },
 
   writing: function () {
-    this._copyProjectFiles();
+    const done = this.async();
+    this._copyProjectFiles()
+    .then(() => {
+      done();
+    })
+    .catch((err)=>{
```
Comment (akrantz) [inline src/app/index.ts]: nit: add spaces around `=>`

File: src/app/index.ts [hunk 3]
```diff
@@ -265,7 +274,13 @@ module.exports = yo.extend({
         // Copy project template files from project repository (currently only custom functions has its own separate repo)
         if (projectRepoBranchInfo.repo)
         {
-          git().clone(projectRepoBranchInfo.repo, this.destinationPath(), ['--branch', (projectRepoBranchInfo.branch) ? projectRepoBranchInfo.branch : 'master']);
+          git().clone(projectRepoBranchInfo.repo, this.destinationPath(), ['--branch', (projectRepoBranchInfo.branch) ? projectRepoBranchInfo.branch : 'master'], (err) => {
+            const gitFolder = this.destinationPath() + '/.git';
+            if (fs.existsSync(gitFolder)){
+              helperMethods.deleteFolderRecursively(gitFolder);
+            }
+            return err? reject(err): resolve();
```
Comment (akrantz) [inline src/app/index.ts]: nit: uses spaces on both sides of `?` and `:`.
 `return err ? reject(err) : resolve();`

Comment (TCourtneyOwen) [reply src/app/index.ts]: Adam, I will make these changes since I have incorporated these changes into another change I am about to send out that calls into office-addin-manifest to modify the manifest guid and display name

Comment (akrantz) [reply src/app/index.ts]: @TCourtneyOwen I think it would be better to merge this first, and then we can merge it into your manifest change branch.

Comment (TCourtneyOwen) [reply src/app/index.ts]: OK, that's fine, but I am going to make these changes as opposed to waiting on Thorsten
